include(FindPackageHandleStandardArgs)
find_package(PkgConfig QUIET)

if(AIRSPYHF_INCLUDE_DIR AND AIRSPYHF_LIBRARY)
    message(STATUS "Checking manual paths for libairspyhf...")
    if(EXISTS "${AIRSPYHF_INCLUDE_DIR}/airspyhf.h" AND EXISTS "${AIRSPYHF_LIBRARY}")
        set(AirspyHF_INCLUDE_DIRS ${AIRSPYHF_INCLUDE_DIR})
        set(AirspyHF_LIBRARIES ${AIRSPYHF_LIBRARY})
        set(AIRSPYHF_FOUND_MANUAL TRUE)
    else()
        message(WARNING "Manual libairspyhf paths specified but invalid/incomplete. Ignoring.")
    endif()
endif()

if(NOT AIRSPYHF_FOUND_MANUAL AND PKG_CONFIG_FOUND)
    message(STATUS "Attempting pkg-config for libairspyhf (native build)...")
    pkg_check_modules(PC_AIRSPYHF QUIET libairspyhf)
    if(PC_AIRSPYHF_FOUND)
        set(AirspyHF_INCLUDE_DIRS ${PC_AIRSPYHF_INCLUDE_DIRS})
        set(AirspyHF_LIBRARIES ${PC_AIRSPYHF_LINK_LIBRARIES})
    endif()
endif()

if(NOT AirspyHF_LIBRARIES)
    message(STATUS "Did not find libairspyhf via manual paths or pkg-config, trying explicit search...")
    find_path(AirspyHF_INCLUDE_DIR NAMES airspyhf.h PATHS /usr/local/include /usr/include)
    find_library(AirspyHF_LIBRARY NAMES airspyhf PATHS /usr/local/lib /usr/lib)
    if(AirspyHF_INCLUDE_DIR AND AirspyHF_LIBRARY)
        set(AirspyHF_INCLUDE_DIRS ${AirspyHF_INCLUDE_DIR})
        set(AirspyHF_LIBRARIES ${AirspyHF_LIBRARY})
    endif()
endif()

find_package_handle_standard_args(AirspyHF REQUIRED_VARS AirspyHF_LIBRARIES AirspyHF_INCLUDE_DIRS)
