include(FindPackageHandleStandardArgs)
find_package(PkgConfig QUIET)

if(RTLSDR_INCLUDE_DIR AND RTLSDR_LIBRARY)
    message(STATUS "Checking manual paths for librtlsdr...")
    if(EXISTS "${RTLSDR_INCLUDE_DIR}/rtl-sdr.h" AND EXISTS "${RTLSDR_LIBRARY}")
        set(RtlSdr_INCLUDE_DIRS ${RTLSDR_INCLUDE_DIR})
        set(RtlSdr_LIBRARIES ${RTLSDR_LIBRARY})
        set(RTLSDR_FOUND_MANUAL TRUE)
    else()
        message(WARNING "Manual librtlsdr paths specified but invalid/incomplete. Ignoring.")
    endif()
endif()

if(NOT RTLSDR_FOUND_MANUAL AND PKG_CONFIG_FOUND)
    message(STATUS "Attempting pkg-config for librtlsdr (native build)...")
    pkg_check_modules(PC_RTLSDR QUIET librtlsdr)
    if(PC_RTLSDR_FOUND)
        set(RtlSdr_INCLUDE_DIRS ${PC_RTLSDR_INCLUDE_DIRS})
        set(RtlSdr_LIBRARIES ${PC_RTLSDR_LINK_LIBRARIES})
    endif()
endif()

if(NOT RtlSdr_LIBRARIES)
    message(STATUS "Did not find librtlsdr via manual paths or pkg-config, trying explicit search...")
    find_path(RtlSdr_INCLUDE_DIR NAMES rtl-sdr.h PATHS /usr/local/include /usr/include)
    find_library(RtlSdr_LIBRARY NAMES rtlsdr PATHS /usr/local/lib /usr/lib)
    if(RtlSdr_INCLUDE_DIR AND RtlSdr_LIBRARY)
        set(RtlSdr_INCLUDE_DIRS ${RtlSdr_INCLUDE_DIR})
        set(RtlSdr_LIBRARIES ${RtlSdr_LIBRARY})
    endif()
endif()

find_package_handle_standard_args(RtlSdr REQUIRED_VARS RtlSdr_LIBRARIES RtlSdr_INCLUDE_DIRS)
