include(FindPackageHandleStandardArgs)
find_package(PkgConfig QUIET)

if(HYDRASDR_INCLUDE_DIR AND HYDRASDR_LIBRARY)
    message(STATUS "Checking manual paths for libhydrasdr...")

    if(EXISTS "${HYDRASDR_INCLUDE_DIR}/hydrasdr.h" AND EXISTS "${HYDRASDR_LIBRARY}")
        set(HydraSDR_INCLUDE_DIRS ${HYDRASDR_INCLUDE_DIR})
        set(HydraSDR_LIBRARIES ${HYDRASDR_LIBRARY})
        set(HYDRASDR_FOUND_MANUAL TRUE)
    else()
        message(WARNING "Manual libhydrasdr paths specified but invalid/incomplete. Ignoring.")
    endif()
endif()

if(NOT HYDRASDR_FOUND_MANUAL AND PKG_CONFIG_FOUND)
    message(STATUS "Attempting pkg-config for libhydrasdr...")
    pkg_check_modules(PC_HYDRASDR QUIET libhydrasdr)
    if(PC_HYDRASDR_FOUND)
        set(HydraSDR_INCLUDE_DIRS ${PC_HYDRASDR_INCLUDE_DIRS})
        set(HydraSDR_LIBRARIES ${PC_HYDRASDR_LINK_LIBRARIES})
    endif()
endif()

if(NOT HydraSDR_LIBRARIES)
    message(STATUS "Did not find libhydrasdr via manual paths or pkg-config, trying explicit search...")
    find_path(HydraSDR_INCLUDE_DIR NAMES hydrasdr.h PATHS /usr/local/include /usr/include)
    find_library(HydraSDR_LIBRARY NAMES hydrasdr PATHS /usr/local/lib /usr/lib)
    if(HydraSDR_INCLUDE_DIR AND HydraSDR_LIBRARY)
        set(HydraSDR_INCLUDE_DIRS ${HydraSDR_INCLUDE_DIR})
        set(HydraSDR_LIBRARIES ${HydraSDR_LIBRARY})
    endif()
endif()

find_package_handle_standard_args(HydraSDR REQUIRED_VARS HydraSDR_LIBRARIES HydraSDR_INCLUDE_DIRS)
