include(FindPackageHandleStandardArgs)
find_package(PkgConfig QUIET)

if(BLADERF_INCLUDE_DIR AND BLADERF_LIBRARY)
    message(STATUS "Checking manual paths for libbladeRF...")
    if(EXISTS "${BLADERF_INCLUDE_DIR}/libbladeRF.h" AND EXISTS "${BLADERF_LIBRARY}")
        set(BladeRF_INCLUDE_DIRS ${BLADERF_INCLUDE_DIR})
        set(BladeRF_LIBRARIES ${BLADERF_LIBRARY})
        set(BLADERF_FOUND_MANUAL TRUE)
    else()
        message(WARNING "Manual libbladeRF paths specified but invalid/incomplete. Ignoring.")
    endif()
endif()

if(NOT BLADERF_FOUND_MANUAL AND PKG_CONFIG_FOUND)
    message(STATUS "Attempting pkg-config for libbladeRF...")
    pkg_check_modules(PC_BLADERF QUIET libbladeRF)
    if(PC_BLADERF_FOUND)
        set(BladeRF_INCLUDE_DIRS ${PC_BLADERF_INCLUDE_DIRS})
        set(BladeRF_LIBRARIES ${PC_BLADERF_LINK_LIBRARIES})
    endif()
endif()

if(NOT BladeRF_LIBRARIES)
    message(STATUS "Did not find libbladeRF via manual paths or pkg-config, trying explicit search...")
    find_path(BladeRF_INCLUDE_DIR NAMES libbladeRF.h)
    find_library(BladeRF_LIBRARY NAMES bladeRF)
    if(BladeRF_INCLUDE_DIR AND BladeRF_LIBRARY)
        set(BladeRF_INCLUDE_DIRS ${BladeRF_INCLUDE_DIR})
        set(BladeRF_LIBRARIES ${BladeRF_LIBRARY})
    endif()
endif()

# CORRECTED LINE BELOW:
find_package_handle_standard_args(BladeRF REQUIRED_VARS BladeRF_LIBRARIES BladeRF_INCLUDE_DIRS)
