include(FindPackageHandleStandardArgs)
find_package(PkgConfig QUIET)

if(AIRSPY_INCLUDE_DIR AND AIRSPY_LIBRARY)
    message(STATUS "Checking manual paths for libairspy...")

    if(EXISTS "${AIRSPY_INCLUDE_DIR}/airspy.h" AND EXISTS "${AIRSPY_LIBRARY}")
        set(Airspy_INCLUDE_DIRS ${AIRSPY_INCLUDE_DIR})
        set(Airspy_LIBRARIES ${AIRSPY_LIBRARY})
        set(AIRSPY_FOUND_MANUAL TRUE)
    else()
        message(WARNING "Manual libairspy paths specified but invalid/incomplete. Ignoring.")
    endif()
endif()

if(NOT AIRSPY_FOUND_MANUAL AND PKG_CONFIG_FOUND)
    message(STATUS "Attempting pkg-config for libairspy...")
    pkg_check_modules(PC_AIRSPY QUIET libairspy)
    if(PC_AIRSPY_FOUND)
        set(Airspy_INCLUDE_DIRS ${PC_AIRSPY_INCLUDE_DIRS})
        set(Airspy_LIBRARIES ${PC_AIRSPY_LINK_LIBRARIES})
    endif()
endif()

if(NOT Airspy_LIBRARIES)
    message(STATUS "Did not find libairspy via manual paths or pkg-config, trying explicit search...")
    find_path(Airspy_INCLUDE_DIR NAMES airspy.h PATHS /usr/local/include /usr/include)
    find_library(Airspy_LIBRARY NAMES airspy PATHS /usr/local/lib /usr/lib)
    if(Airspy_INCLUDE_DIR AND Airspy_LIBRARY)
        set(Airspy_INCLUDE_DIRS ${Airspy_INCLUDE_DIR})
        set(Airspy_LIBRARIES ${Airspy_LIBRARY})
    endif()
endif()

find_package_handle_standard_args(Airspy REQUIRED_VARS Airspy_LIBRARIES Airspy_INCLUDE_DIRS)
