include(FindPackageHandleStandardArgs)
find_package(PkgConfig QUIET)

if(LIBUSB_INCLUDE_DIR AND LIBUSB_LIBRARY)
    message(STATUS "Checking manual paths for libusb-1.0...")
    if(EXISTS "${LIBUSB_INCLUDE_DIR}/libusb.h" AND EXISTS "${LIBUSB_LIBRARY}")
        set(LibUSB_INCLUDE_DIRS ${LIBUSB_INCLUDE_DIR})
        set(LibUSB_LIBRARIES ${LIBUSB_LIBRARY})
        set(LIBUSB_FOUND_MANUAL TRUE)
    else()
        message(WARNING "Manual libusb-1.0 paths specified but invalid/incomplete. Ignoring.")
    endif()
endif()

if(NOT LIBUSB_FOUND_MANUAL AND PKG_CONFIG_FOUND)
    message(STATUS "Attempting pkg-config for libusb-1.0...")
    pkg_check_modules(PC_LIBUSB QUIET libusb-1.0)
    if(PC_LIBUSB_FOUND)
        set(LibUSB_INCLUDE_DIRS ${PC_LIBUSB_INCLUDE_DIRS})
        set(LibUSB_LIBRARIES ${PC_LIBUSB_LINK_LIBRARIES})
    endif()
endif()

if(NOT LibUSB_LIBRARIES)
    message(STATUS "Did not find libusb-1.0 via manual paths or pkg-config, trying find_package...")
    find_path(LibUSB_INCLUDE_DIR NAMES libusb.h PATH_SUFFIXES libusb-1.0)
    find_library(LibUSB_LIBRARY NAMES usb-1.0)
    if(LibUSB_INCLUDE_DIR AND LibUSB_LIBRARY)
        set(LibUSB_INCLUDE_DIRS ${LibUSB_INCLUDE_DIR})
        set(LibUSB_LIBRARIES ${LibUSB_LIBRARY})
    endif()
endif()

find_package_handle_standard_args(LibUSB REQUIRED_VARS LibUSB_LIBRARIES LibUSB_INCLUDE_DIRS)
