include(FindPackageHandleStandardArgs)
find_package(PkgConfig QUIET)

if(HACKRF_INCLUDE_DIR AND HACKRF_LIBRARY)
    message(STATUS "Checking manual paths for libhackrf...")
    if(EXISTS "${HACKRF_INCLUDE_DIR}/hackrf.h" AND EXISTS "${HACKRF_LIBRARY}")
        set(HackRF_INCLUDE_DIRS ${HACKRF_INCLUDE_DIR})
        set(HackRF_LIBRARIES ${HACKRF_LIBRARY})
        set(HACKRF_FOUND_MANUAL TRUE)
    else()
        message(WARNING "Manual libhackrf paths specified but invalid/incomplete. Ignoring.")
    endif()
endif()

if(NOT HACKRF_FOUND_MANUAL AND PKG_CONFIG_FOUND)
    message(STATUS "Attempting pkg-config for libhackrf (native build)...")
    pkg_check_modules(PC_HACKRF QUIET libhackrf)
    if(PC_HACKRF_FOUND)
        set(HackRF_INCLUDE_DIRS ${PC_HACKRF_INCLUDE_DIRS})
        set(HackRF_LIBRARIES ${PC_HACKRF_LINK_LIBRARIES})
    endif()
endif()

if(NOT HackRF_LIBRARIES)
    message(STATUS "Did not find libhackrf via manual paths or pkg-config, trying explicit search...")
    find_path(HackRF_INCLUDE_DIR NAMES hackrf.h)
    find_library(HackRF_LIBRARY NAMES hackrf)
    if(HackRF_INCLUDE_DIR AND HackRF_LIBRARY)
        set(HackRF_INCLUDE_DIRS ${HackRF_INCLUDE_DIR})
        set(HackRF_LIBRARIES ${HackRF_LIBRARY})
    endif()
endif()

find_package_handle_standard_args(HackRF REQUIRED_VARS HackRF_LIBRARIES HackRF_INCLUDE_DIRS)
