include(FindPackageHandleStandardArgs)
find_package(PkgConfig QUIET)

if(EXPAT_INCLUDE_DIR AND EXPAT_LIBRARY)
    message(STATUS "Checking manual paths for Expat...")
    if(EXISTS "${EXPAT_INCLUDE_DIR}/expat.h" AND EXISTS "${EXPAT_LIBRARY}")
        set(Expat_INCLUDE_DIRS ${EXPAT_INCLUDE_DIR})
        set(Expat_LIBRARIES ${EXPAT_LIBRARY})
        set(EXPAT_FOUND_MANUAL TRUE)
    else()
        message(WARNING "Manual Expat paths specified but invalid/incomplete. Ignoring.")
    endif()
endif()

if(NOT EXPAT_FOUND_MANUAL AND PKG_CONFIG_FOUND)
    message(STATUS "Attempting pkg-config for Expat...")
    pkg_check_modules(PC_EXPAT QUIET expat)
    if(PC_EXPAT_FOUND)
        set(Expat_INCLUDE_DIRS ${PC_EXPAT_INCLUDE_DIRS})
        set(Expat_LIBRARIES ${PC_EXPAT_LINK_LIBRARIES})
    endif()
endif()

if(NOT Expat_LIBRARIES)
    message(STATUS "Did not find Expat via manual paths or pkg-config, trying find_package...")
    find_package(EXPAT QUIET)
    if(EXPAT_FOUND)
        set(Expat_INCLUDE_DIRS ${EXPAT_INCLUDE_DIRS})
        set(Expat_LIBRARIES ${EXPAT_LIBRARIES})
    endif()
endif()

find_package_handle_standard_args(Expat REQUIRED_VARS Expat_LIBRARIES Expat_INCLUDE_DIRS)
