include(FindPackageHandleStandardArgs)
find_package(PkgConfig QUIET)

if(SNDFILE_INCLUDE_DIR AND SNDFILE_LIBRARY)
    message(STATUS "Checking manual paths for libsndfile...")
    if(EXISTS "${SNDFILE_INCLUDE_DIR}/sndfile.h" AND EXISTS "${SNDFILE_LIBRARY}")
        set(SndFile_INCLUDE_DIRS ${SNDFILE_INCLUDE_DIR})
        set(SndFile_LIBRARIES ${SNDFILE_LIBRARY})
        set(SNDFILE_FOUND_MANUAL TRUE)
    else()
        message(WARNING "Manual libsndfile paths specified but invalid/incomplete. Ignoring.")
    endif()
endif()

if(NOT SNDFILE_FOUND_MANUAL AND PKG_CONFIG_FOUND)
    message(STATUS "Attempting pkg-config for libsndfile (native build)...")
    pkg_check_modules(PC_SNDFILE QUIET sndfile)
    if(PC_SNDFILE_FOUND)
        set(SndFile_INCLUDE_DIRS ${PC_SNDFILE_INCLUDE_DIRS})
        set(SndFile_LIBRARIES ${PC_SNDFILE_LINK_LIBRARIES})
    endif()
endif()

if(NOT SndFile_LIBRARIES)
    if(CMAKE_CROSSCOMPILING)
        message(STATUS "Attempting find_package for libsndfile (cross-compile)...")
    else()
        message(STATUS "Did not find libsndfile via manual paths or pkg-config, trying find_package...")
    endif()
    
    find_path(SndFile_INCLUDE_DIR sndfile.h)
    find_library(SndFile_LIBRARY sndfile)
    if(SndFile_INCLUDE_DIR AND SndFile_LIBRARY)
        set(SndFile_INCLUDE_DIRS ${SndFile_INCLUDE_DIR})
        set(SndFile_LIBRARIES ${SndFile_LIBRARY})
    endif()
endif()

find_package_handle_standard_args(SndFile REQUIRED_VARS SndFile_LIBRARIES SndFile_INCLUDE_DIRS)
