name: Codacy Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '19 18 * * 6'

permissions:
  contents: read

jobs:
  codacy-security-scan:
    permissions:
      contents: read
      security-events: write
      actions: read

    name: Codacy Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          format: sarif
          output: results.sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 2147483647
          upload: false

      - name: Combine all SARIF runs by tool name
        shell: bash
        run: |
          jq '.runs |= (group_by(.tool.driver.name) | map(.[0] + {results: map(.results) | add})) | del(.runs[].results[].partialFingerprints?)' results.sarif > results-combined.sarif

      - name: Upload Codacy SARIF results file
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results-combined.sarif
